// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentStore.WebApi.Controllers.DocumentController.AddDocument(Microsoft.AspNetCore.Http.IFormFile)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentStore.WebApi.Controllers.DocumentController.Delete(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentStore.WebApi.Controllers.DocumentController.Get(DocumentStore.WebApi.Controllers.DocumentParameters)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentStore.WebApi.Controllers.DocumentController.GetByLocation(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentStore.WebApi.Controllers.DocumentController.ReadFileContent(Microsoft.AspNetCore.Http.IFormFile)~System.Threading.Tasks.Task{System.Byte[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:DocumentStore.WebApi.Middleware.ErrorWrappingMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]
